### ISSUE TITLE
What is the name of the font used in the screenshot of code ?

### ISSUE THREAD

**Issue by cata0309** [OlyaB/CyanTheme#6]

**Comment by OlyaB** [comment]
Hello! I'm going to ask our designer. Why do you ask? :)

**Comment by cata0309** [comment]
I want to use it too in my IDE with the CyanTheme

mar., 9 iul. 2019, 11:50 Olga Berdnikova <notifications@github.com> a scris:

**Comment by OlyaB** [comment]
This is a new font. It is currently in the private alpha stage. If you'd like, I can share it with you when it's in public beta.

**Comment by cata0309** [comment]
You can send me a copy via email catalinmarincia@gmail.com, I am trusty and
I can surely say that it will remain private

mar., 9 iul. 2019, 13:09 Olga Berdnikova <notifications@github.com> a scris:

**Comment by cata0309** [comment]
Can you offer any details about when will it be in public beta ?

**Comment by OlyaB** [comment]
Sorry, cannot share any details yet. This is still early in the process.

**Comment by cata0309** [comment]
Any news about the font ?

**Comment by OlyaB** [comment]
https://www.jetbrains.com/lp/mono/

**Comment by cata0309** [comment]
Thank you ! I have been using it for a week and didn't notice it was this font. I am sorry about that !
