### ISSUE TITLE
代码提示字体颜色和背景冲突了吧

### ISSUE THREAD

**Issue by Liang-Dongxing** [OlyaB/CyanTheme#7]
![U1SUB` 7 X %W{HT%4GJ_SU](https://user-images.githubusercontent.com/19583575/60790566-639d5d80-a194-11e9-9869-e8d81bb2e213.png)
这个是191的

**Comment by Liang-Dongxing** [comment]
![L8@L06 1N`W(3~UBO)X~05A](https://user-images.githubusercontent.com/19583575/60790919-27b6c800-a195-11e9-8518-03154fd9f91f.png)
这个是192中的

**Comment by Liang-Dongxing** [comment]
都有点看不清啊

**Comment by IgorPerikov** [comment]
I hope google translate made a good job, so probably I have the same feeling about latest update - highlighted string in auto-completion pop-up is **very** hard to read, any thoughts, @OlyaB ?

**Comment by OlyaB** [comment]
Thanks for reporting! Fixed
